 #start style
style = [
        self.setStyleSheet("myWindow{"
                           "background:	white;}"
                           "QLabel{"
                           "font-size:15px;"
                           "font-family:Arial;"
                           "color:#387791;}"
                           "QLineEdit{"
                           "background:white;"
                           "font-size:14px;"
                           "font-family:Arial;"
                           "border:2px solid;"
                           "border-radius:5px;"
                           "border-color:#839CC9;"
                           "padding-left:15px;"
                           "margin:2px;}"),
        self.add_file_button.setStyleSheet(
            "QPushButton {background-color:white;"
            " color: #839CC9;"
            "font-family:Arial Black;"
            " border-radius: 4px;"
            "font-size:25px; "
            "padding:25px;"
            "margin-left:100px;}"),

        self.button_task_excel_4.setStyleSheet(
            "QPushButton {background-color:white;"
            " color: #839CC9;"
            "margin:5px;"
            "align-text:left;"
            "font-family:Arial Black;"
            "width:500px;"
            "height:25px;"
            " border-radius: 4px;"
            "font-size:15px; "
            "padding:25px 0px 25px 0px;"
            "border:2px;"
            "border-color:#839CC9;"
            "border-style:solid;}"
            "QPushButton:hover{background:#E2F9FF;}"
            "QPushButton:pressed {background-color:#E2F9FF ; border:7px ;border-style:solid; border-color:#839CC9;}"
        ),
        self.button_task_excel_3.setStyleSheet(
            "QPushButton {background-color:white;"
            " color: #839CC9;"
            "margin:5px;"
            "align-text:left;"
            "font-family:Arial Black;"
            "width:500px;"
            "height:25px;"
            " border-radius: 4px;"
            "font-size:15px; "
            "padding:25px 0px 25px 0px;"
            "border:2px;"
            "border-color:#839CC9;"
            "border-style:solid;}"
            "QPushButton:hover{background:#E2F9FF;}"
            "QPushButton:pressed {background-color:#E2F9FF ; border:7px ;border-style:solid; border-color:#839CC9;}"
        ),
        self.button_task_excel_2.setStyleSheet(
            "QPushButton {background-color:white;"
            " color: #839CC9;"
            "margin:5px;"
            "align-text:left;"
            "font-family:Arial Black;"
            "width:500px;"
            "height:25px;"
            " border-radius: 4px;"
            "font-size:15px; "
            "padding:25px 0px 25px 0px;"
            "border:2px;"
            "border-color:#839CC9;"
            "border-style:solid;}"
            "QPushButton:hover{background:#E2F9FF;}"
            "QPushButton:pressed {background-color:#E2F9FF ; border:7px ;border-style:solid; border-color:#839CC9;}"
        ),
        self.button_task_excel_1.setStyleSheet(
            "QPushButton {background-color:white;"
            " color: #839CC9;"
            "margin:5px;"
            "align-text:left;"
            "font-family:Arial Black;"
            "width:500px;"
            "height:25px;"
            " border-radius: 4px;"
            "font-size:15px; "
            "padding:25px 0px 25px 0px;"
            "border:2px;"
            "border-color:#839CC9;"
            "border-style:solid;}"
            "QPushButton:hover{background:#E2F9FF;}"
            "QPushButton:pressed {background-color:#E2F9FF ; border:7px ;border-style:solid; border-color:#839CC9;}"
        ),
        self.button_task_acess_1.setStyleSheet(
            "QPushButton {background-color:white;"
            " color: #839CC9;"
            "margin:5px;"
            "align-text:left;"
            "font-family:Arial Black;"
            "width:500px;"
            "height:25px;"
            " border-radius: 4px;"
            "font-size:15px; "
            "padding:25px 0px 25px 0px;"
            "border:2px;"
            "border-color:#839CC9;"
            "border-style:solid;}"
            "QPushButton:hover{background:#E2F9FF;}"
            "QPushButton:pressed {background-color:#E2F9FF ; border:7px ;border-style:solid; border-color:#839CC9;}"
        ),
        self.button_zip_acess.setStyleSheet("QPushButton {background-color:white;"
            " color: #839CC9;"
            "margin:5px;"
            "font-family:Arial Black;"
            "width:500px;"
            "height:25px;"
            " border-radius: 4px;"
            "font-size:15px; "
            "padding:25px 40px 25px 0px;"
            "border:2px;"
            "border-color:#839CC9;"
            "border-style:solid;}"
            "QPushButton:hover{background:#E2F9FF;}"
            "QPushButton:pressed {background-color:#E2F9FF ; border:7px ;border-style:solid; border-color:#839CC9;}"),

        self.power_point_task.setStyleSheet("QPushButton {background-color:white;"
            " color: #839CC9;"
            "margin:5px;"
            "font-family:Arial Black;"
            "width:500px;"
            "height:25px;"
            " border-radius: 4px;"
            "font-size:15px; "
            "padding:25px 40px 25px 0px;"
            "border:2px;"
            "border-color:#839CC9;"
            "border-style:solid;}"
            "QPushButton:hover{background:#E2F9FF;}"
            "QPushButton:pressed {background-color:#E2F9FF ; border:7px ;border-style:solid; border-color:#839CC9;}"),

        self.power_point_zip.setStyleSheet("QPushButton {background-color:white;"
            " color: #839CC9;"
            "margin:5px;"
            "font-family:Arial Black;"
            "width:500px;"
            "height:25px;"
            " border-radius: 4px;"
            "font-size:15px; "
            "padding:25px 40px 25px 0px;"
            "border:2px;"
            "border-color:#839CC9;"
            "border-style:solid;}"
            "QPushButton:hover{background:#E2F9FF;}"
            "QPushButton:pressed {background-color:#E2F9FF ; border:7px ;border-style:solid; border-color:#839CC9;}"),

        self.button_task_word_1.setStyleSheet(
            "QPushButton {background-color:white;"
            " color: #839CC9;"
            "margin:5px;"
            "align-text:left;"
            "font-family:Arial Black;"
            "width:500px;"
            "height:25px;"
            " border-radius: 4px;"
            "font-size:15px; "
            "padding:25px 0px 25px 0px;"
            "border:2px;"
            "border-color:#839CC9;"
            "border-style:solid;}"
            "QPushButton:hover{background:#E2F9FF;}"
            "QPushButton:pressed {background-color:#E2F9FF ; border:7px ;border-style:solid; border-color:#839CC9;}"
        ),
        self.button_task_word_2.setStyleSheet(
            "QPushButton {background-color:white;"
            " color: #839CC9;"
            "margin:5px;"
            "font-family:Arial Black;"
            "align-text:left;"
            "width:500px;"
            "height:18px;"
            " border-radius: 4px;"
            "font-size:15px; "
            "padding:25px 10px 25px 0px;"
            "border:2px;"
            "border-color:#839CC9;"
            "border-style:solid;}"
            "QPushButton:hover{background:#E2F9FF;}"
            "QPushButton:pressed {background-color:#E2F9FF ; border:7px ;border-style:solid; border-color:#839CC9;}"
        ),
        self.button_task_word_3.setStyleSheet(
            "QPushButton {background-color:white;"
            " color: #839CC9;"
            "margin:5px;"
            "font-family:Arial Black;"
            "width:500px;"
            "height:25px;"
            " border-radius: 4px;"
            "font-size:15px; "
            "padding:25px 40px 25px 0px;"
            "border:2px;"
            "border-color:#839CC9;"
            "border-style:solid;}"
            "QPushButton:hover{background:#E2F9FF;}"
            "QPushButton:pressed {background-color:#E2F9FF ; border:7px ;border-style:solid; border-color:#839CC9;}"
        ),
        self.button_task_word_4.setStyleSheet("QPushButton {background-color:white;"
            " color: #839CC9;"
            "margin:5px;"
            "font-family:Arial Black;"
            "width:500px;"
            "height:25px;"
            " border-radius: 4px;"
            "font-size:15px; "
            "padding:25px 40px 25px 0px;"
            "border:2px;"
            "border-color:#839CC9;"
            "border-style:solid;}"
            "QPushButton:hover{background:#E2F9FF;}"
            "QPushButton:pressed {background-color:#E2F9FF ; border:7px ;border-style:solid; border-color:#839CC9;}"),

        self.submit_button.setStyleSheet(
            "QPushButton {background-color:white;"
            " color: #839CC9;"
            "font-family:Arial Black;"
            " border-radius: 4px;"
            "font-size:25px; "
            "padding:25px;"
            "border:4px;"
            "border-color:#839CC9;"
            "border-style:solid;}"
            "QPushButton:hover{background:#E2F9FF;}"
            "QPushButton:pressed {background-color:#E2F9FF ; border:7px ;border-style:solid; border-color:#839CC9;}"
        ),

        self.emailMessage.setStyleSheet("background:white;"
                                        "font-size:14px;"
                                        "font-family:Arial;"
                                        "border: 2px solid #839CC9;"
                                        "border-radius:5px;"
                                        "padding-left:15px;"
                                        "margin:2px;"),
        self.button_mail.setStyleSheet(
            "QPushButton {background-color:white;"
            " color: #839CC9;"
            "font-family:Arial Black;"
            " border-radius: 4px;"
            "font-size:25px; "
            "padding:25px;"
            "border:4px;"
            "border-color:#839CC9;"
            "border-style:solid;}"
            "QPushButton:hover{background:#E2F9FF;}"
            "QPushButton:pressed {background-color:#E2F9FF ; border:7px ;border-style:solid; border-color:#839CC9;}"
        ),
        self.button_users.setStyleSheet(
            "QPushButton {background-color:white;"
            " color: #839CC9;"
            "font-family:Arial Black;"
            " border-radius: 4px;"
            "font-size:25px; "
            "padding:25px;"
            "border:4px;"
            "border-color:#839CC9;"
            "border-style:solid;}"
            "QPushButton:hover{background:#E2F9FF;}"
            "QPushButton:pressed {background-color:#E2F9FF ; border:7px ;border-style:solid; border-color:#839CC9;}"
        ),

        self.button_tasks.setStyleSheet(
            "QPushButton {background-color:white;"
            " color: #839CC9;"
            "font-family:Arial Black;"
            " border-radius: 4px;"
            "font-size:25px; "
            "padding:25px;"
            "border:4px;"
            "border-color:#839CC9;"
            "border-style:solid;}"
            "QPushButton:hover{background:#E2F9FF;}"
            "QPushButton:pressed {background-color:#E2F9FF ; border:7px ;border-style:solid; border-color:#839CC9;}"
        ),

        self.button_list.setStyleSheet(
            "QPushButton {background-color:white;"
            " color: #839CC9;"
            "font-family:Arial Black;"
            " border-radius: 4px;"
            "font-size:25px; "
            "padding:25px;"
            "border:4px;"
            "border-color:#839CC9;"
            "border-style:solid;}"
            "QPushButton:hover{background:#E2F9FF;}"
            "QPushButton:pressed {background-color:#E2F9FF ; border:7px ;border-style:solid; border-color:#839CC9;}"
        ),

        self.NameUser.setStyleSheet("QLabel{font-size:25px;"
                                    "background-color:white;"
                                    "border:3px;"
                                    "border-style:solid;"
                                    "border-color:#839CC9;"
                                    "margin:5px;}"),
        self.emailUser.setStyleSheet("QLabel{font-size:25px;"
                                     "background-color:white;"
                                     "border:3px;"
                                     "border-style:solid;"
                                     "border-color:#839CC9;"
                                     "margin:5px;}"),
        self.button_exit.setStyleSheet(
            "QPushButton {background-color:white;"
            " color: #839CC9;"
            "font-family:Arial Black;"
            " border-radius: 4px;"
            "font-size:25px; "
            "padding:25px;"
            "border:4px;"
            "border-color:#839CC9;"
            "border-style:solid;}"
            "QPushButton:hover{background:#E2F9FF;}"
            "QPushButton:pressed {background-color:#E2F9FF ; border:7px ;border-style:solid; border-color:#839CC9;}"
        ),

        self.percentPerfomenceUser.setStyleSheet("QLabel{font-size:25px;"
                                                 "background-color:white;"
                                                 "border:3px;"
                                                 "border-style:solid;"
                                                 "border-color:#839CC9;"
                                                 "margin:5px;}"),
        self.averagePointUser.setStyleSheet("QLabel{font-size:25px;"
                                            "background-color:white;"
                                            "border:3px;"
                                            "border-style:solid;"
                                            "border-color:#839CC9;"
                                            "margin:5px;}"),
        self.LastNameUser.setStyleSheet("QLabel{font-size:25px;"
                                        "background-color:white;"
                                        "border:3px;"
                                        "border-style:solid;"
                                        "border-color:#839CC9;"
                                        "margin:5px;}"),
        self.combobox_user.setStyleSheet("QComboBox{"
                                         "font-size:15px;"
                                         "margin:5px;"
                                         "background:white;"
                                         "padding:5px;"
                                         "border:3px solid #839CC9;}")
        self.combobox_download.setStyleSheet("QComboBox{"
                                             "font-size:15px;"
                                             "margin:3px;"
                                             "background:white;"
                                             "padding:5px;"
                                             "border:3px solid #839CC9;}")
        self.info.setStyleSheet("QLabel{" "font-size:25px;}"),
        ]
        #end style
        #---------------------------------------------------------------